<a href="https://colab.research.google.com/github/yannisyeung/QM2/blob/main/QM_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Replace 'file_path.csv' with the actual path to your CSV file
data = pd.read_csv('TheTrace.csv')

In [ ]:
import pylab
import matplotlib.pyplot as plt
# make the plots a little wider by default
%matplotlib inline
plt.style.use('ggplot')

pylab.rcParams['figure.figsize'] = (10., 8.)

data = pd.read_csv('TheTrace.csv')

display(data)

,Incident ID,Incident Date,State,City Or County,Address,Victims Killed,Victims Injured,Suspects Killed,Suspects Injured,Suspects Arrested,Operations
0,3074550,"November 18, 2024",Colorado,Denver,7150 Leetsdale Dr,0,4,0,0,1,NaN
1,3074150,"November 17, 2024",Louisiana,New Orleans,1841 Almonaster Ave,0,10,0,0,1,NaN
2,3074162,"November 17, 2024",Mississippi,Sandy Hook,50 block of Sunlight Church Rd,1,3,0,0,1,NaN
3,3074461,"November 17, 2024",Ohio,Columbus,1700 block of Parsons Ave,0,4,0,0,0,NaN
4,3073211,"November 16, 2024",California,Lancaster,44502 N Tabler Ave,4,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1995,2104725,"August 31, 2021",North Carolina,Elm City,3500 block of London Church Rd,2,2,0,0,1,NaN
1996,2104181,"August 30, 2021",Illinois,Normal,2000 block of Lambert Dr,2,3,1,0,0,NaN
1997,2103256,"August 29, 2021",Tennessee,Nashville,2621 Jefferson St,0,5,0,0,1,NaN
1998,2102991,"August 29, 2021",Nevada,Las Vegas,1750 S Rainbow Blvd,1,3,0,0,3,NaN
1999,2103311,"August 29, 2021",Wisconsin,Milwaukee,N 41st St and W Lloyd St,0,4,0,0,0,NaN

In [ ]:
from IPython.display import display

display(texas_data)

,Incident ID,Incident Date,State,City Or County,Address,Victims Killed,Victims Injured,Suspects Killed,Suspects Injured,Suspects Arrested,Operations
29,3057226,"October 27, 2024",Texas,Corpus Christi,5400 block of S Staples St,2,2,0,0,0,NaN
30,3057212,"October 27, 2024",Texas,Corpus Christi,1000 block of Winnebago St,0,5,0,0,0,NaN
35,3056266,"October 24, 2024",Texas,Waco,1700 block of N 7th St,0,4,0,0,0,NaN
51,3041753,"October 6, 2024",Texas,Fort Worth,100 block of NW 24th St,1,5,0,0,1,NaN
73,3024007,"September 14, 2024",Texas,Houston,4901 Laura Koppe Rd,3,8,0,0,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1925,2131406,"October 2, 2021",Texas,San Antonio,6222 S New Braunfels Ave,1,3,0,0,0,NaN
1952,2119745,"September 19, 2021",Texas,Dallas,100 block of N Malcolm X Blvd,2,4,0,0,2,NaN
1963,2114626,"September 12, 2021",Texas,Temple,900 block of S 24th St,0,4,0,0,1,NaN
1980,2108414,"September 5, 2021",Texas,Houston,7518 Imogene St,4,0,0,0,0,NaN
1991,2107621,"September 3, 2021",Texas,Austin,9345 US-290,1,3,0,0,0,NaN

In [ ]:
# Filter data for Texas
texas_data_data = data[data['State'] == 'texas']

# Calculate the mean of the 'Victims Killed' column in California
mean_texas_victims = texas_data['Victims Killed'].mean()

# Print the result
print(f"The mean of Victims Killed in texas is: {mean_texas_victims}")

The mean of Victims Killed in texas is: 1.3374233128834356

In [ ]:
# Filter data for Texas
texas_data_data = data[data['State'] == 'Texas']

# Calculate the median of the 'Victims Killed' column in Texas
median_texas_victims = texas_data['Victims Killed'].median()

# Print the result
print(f"The median of Victims Killed in Texas is: {median_texas_victims}")

The median of Victims Killed in Texas is: 1.0

In [ ]:
# Filter data for Texas
texas_data = data[data['State'] == 'Texas']

# Calculate the mode of the 'Victims Killed' column for Texas
mode_texas_victims = texas_data['Victims Killed'].mode()

# Print the result
print(f"The mode of Victims Killed in Texas is: {mode_texas_victims[0]}")

The mode of Victims Killed in Texas is: 0

In [ ]:
# Filter data for Texas
texas_data = data[data['State'] == 'Texas']

# Calculate the standard deviation of the 'Victims Killed' column in California
std_dev_texas_victims = texas_data_data['Victims Killed'].std()

# Print the result
print(f"The standard deviation of Victims Killed in Texas is: {std_dev_texas_victims}")

The standard deviation of Victims Killed in Texas is: 2.1292230626602437

In [ ]:
# Filter data for Texas
texas_data = data[data['State'] == 'Texas']

# Calculate the 25th (Q1) and 75th (Q3) percentiles in texas data
Q1_texas = texas_data['Victims Killed'].quantile(0.25)
Q3_texas = texas_data['Victims Killed'].quantile(0.75)

# Calculate the IQR in California
IQR_texas = Q3_texas - Q1_texas

# Define the lower and upper bounds for outliers in California
lower_bound_texas = Q1_texas - 1.5 * IQR_texas
upper_bound_texas = Q3_texas + 1.5 * IQR_texas

# Filter outliers in Texas data
outliers_texas = texas_data[(texas_data['Victims Killed'] < lower_bound_texas) |
                                      (texas_data['Victims Killed'] > upper_bound_texas)]

# Display the outliers in Texas
print(f"Number of outliers in texas: {outliers_texas.shape[0]}")
print(outliers_texas.head())

Number of outliers in texas: 4
      Incident ID     Incident Date  State City Or County             Address  \
491       2771255  December 5, 2023  Texas         Austin     7104 Berkman Dr
919       2590046       May 6, 2023  Texas          Allen      820 W Stacy Rd
1556      2310278      May 24, 2022  Texas         Uvalde  715 Old Carrizo Rd
1730      2227058  February 5, 2022  Texas      Corsicana      2919 W 2nd Ave

      Victims Killed  Victims Injured  Suspects Killed  Suspects Injured  \
491                6                3                0                 0
919                8                7                1                 0
1556              21               17                1                 0
1730               7                0                1                 0

      Suspects Arrested  Operations
491                   1         NaN
919                   0         NaN
1556                  0         NaN
1730                  0         NaN

In [ ]:
# Filter data for California
texas_data_data = data[data['State'] == 'Texas']

# Calculate the 25th (Q1) and 75th (Q3) percentiles in Texas data
Q1_texas= texas_data_data['Victims Killed'].quantile(0.25)
Q3_texas = texas_data_data['Victims Killed'].quantile(0.75)

# Calculate the IQR in Texas
IQR_texas = Q3_texas - Q1_texas

# Print the result
print(f"The IQR of Victims Killed in Texas is: {IQR_texas}")

The IQR of Victims Killed in Texas is: 2.0

In [ ]:
texas_data_data = data[data['State'] == 'California']

# Calculate the mean of the 'Victims Killed' column in California
mean_texas_victims = california_data['Victims Killed'].mean()

# Print the result
print(f"The mean of Victims Killed in California is: {mean_california_victims}")

The mean of Victims Killed in California is: 1.2905405405405406

In [ ]:
# Filter data for California
california_data = data[data['State'] == 'California']

# Calculate the median of the 'Victims Killed' column in California
median_california_victims = california_data['Victims Killed'].median()

# Print the result
print(f"The median of Victims Killed in California is: {median_california_victims}")

The median of Victims Killed in California is: 1.0

In [ ]:
# Filter data for California
california_data = data[data['State'] == 'California']

# Calculate the mode of the 'Victims Killed' column in California
mode_california_victims = california_data['Victims Killed'].mode()

# Print the result
print(f"The mode of Victims Killed in California is: {mode_california_victims}")

The mode of Victims Killed in California is: 0    0
Name: Victims Killed, dtype: int64

In [ ]:
# Filter data for California
california_data = data[data['State'] == 'California']

# Calculate the standard deviation of the 'Victims Killed' column in California
std_dev_california_victims = california_data['Victims Killed'].std()

# Print the result
print(f"The standard deviation of Victims Killed in California is: {std_dev_california_victims}")

The standard deviation of Victims Killed in California is: 1.629879918695144

In [ ]:
# Filter data for California
california_data = data[data['State'] == 'California']

# Calculate the 25th (Q1) and 75th (Q3) percentiles in California data
Q1_california = california_data['Victims Killed'].quantile(0.25)
Q3_california = california_data['Victims Killed'].quantile(0.75)

# Calculate the IQR in California
IQR_california = Q3_california - Q1_california

# Print the result
print(f"The IQR of Victims Killed in California is: {IQR_california}")

The IQR of Victims Killed in California is: 2.0

In [ ]:
# Filter data for California
california_data = data[data['State'] == 'California']

# Calculate the 25th (Q1) and 75th (Q3) percentiles in California data
Q1_california = california_data['Victims Killed'].quantile(0.25)
Q3_california = california_data['Victims Killed'].quantile(0.75)

# Calculate the IQR in California
IQR_california = Q3_california - Q1_california

# Define the lower and upper bounds for outliers in California
lower_bound_california = Q1_california - 1.5 * IQR_california
upper_bound_california = Q3_california + 1.5 * IQR_california

# Filter outliers in California data
outliers_california = california_data[(california_data['Victims Killed'] < lower_bound_california) |
                                      (california_data['Victims Killed'] > upper_bound_california)]

# Display the outliers in California
print(f"Number of outliers in California: {outliers_california.shape[0]}")
print(outliers_california.head())

Number of outliers in California: 4
      Incident ID     Incident Date       State City Or County  \
438       2809998  January 23, 2024  California       Adelanto
1086      2509663  January 23, 2023  California  Half Moon Bay
1091      2507836  January 21, 2023  California  Monterey Park
1093      2503345  January 16, 2023  California         Goshen

                                 Address  Victims Killed  Victims Injured  \
438   Shadow Mountain Rd and Lessing Ave               6                0
1086                  12761 San Mateo Rd               7                1
1091                    122 W Garvey Ave              11                9
1093               Harvest Ave and Rd 68               6                0

      Suspects Killed  Suspects Injured  Suspects Arrested  Operations
438                 0                 0                  5         NaN
1086                0                 0                  1         NaN
1091                1                 0                  0         NaN
1093                0                 0                  2         NaN

In [ ]:
from IPython.display import display

display(california_data)

,Incident ID,Incident Date,State,City Or County,Address,Victims Killed,Victims Injured,Suspects Killed,Suspects Injured,Suspects Arrested,Operations
4,3073211,"November 16, 2024",California,Lancaster,44502 N Tabler Ave,4,0,0,0,0,NaN
5,3073900,"November 16, 2024",California,Riverside,11240 Town and Country Dr,0,4,0,0,1,NaN
6,3073377,"November 15, 2024",California,National City,1003 N Ave,1,4,0,0,0,NaN
28,3057339,"October 27, 2024",California,Redding,21199 CA-299,1,5,0,0,1,NaN
33,3057300,"October 26, 2024",California,Fresno,L St and Amador St,0,6,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1877,2148891,"October 23, 2021",California,Ontario,700 block of E Bonnie Brae Ct,1,4,0,0,2,NaN
1936,2125953,"September 26, 2021",California,Oakland,1400 block of 8th Ave,0,4,0,0,0,NaN
1940,2125227,"September 25, 2021",California,Riverside,Mockingbird Canyon Rd and Mariposa Ave,0,6,0,0,0,NaN
1942,2124887,"September 24, 2021",California,Los Angeles,11724 Wilmington Ave,0,4,0,0,2,NaN
1951,2119736,"September 19, 2021",California,Oakland,300 block of 17th St,1,3,0,0,0,NaN

In [ ]:
california_data = data[data['State'] == 'California']

# Calculate the mean of the 'Victims Killed' column in California
mean_california_victims = california_data['Victims Killed'].mean()

# Print the result
print(f"The mean of Victims Killed in California is: {mean_california_victims}")

The mean of Victims Killed in California is: 1.2905405405405406

Finding the decriptive stats for California pre Bill 2015-2018

In [ ]:
import pandas as pd
import os

# List of CSV files to merge
csv_files = ['2014.csv', '2015.csv', '2016.csv', '2017.csv', '2018.csv', '2019.csv','2020.csv', 'TheTrace.csv']  # Add the paths to your files

# List to store individual DataFrames
dataframes = []

# Loop through the files and read each CSV file
for file in csv_files:
    df = pd.read_csv(file)
    dataframes.append(df)

# Concatenate all DataFrames into one
merged_data = pd.concat(dataframes, ignore_index=True)


# Optionally, save the merged data to a new CSV file
merged_data.to_csv('merged_file.csv', index=False)

# Just type the DataFrame name
merged_data

,Incident ID,Incident Date,State,City Or County,Address,Victims Killed,Victims Injured,Suspects Killed,Suspects Injured,Suspects Arrested,Operations
0,271363,"December 29, 2014",Louisiana,New Orleans,Poydras and Bolivar,0,4,0,0,0,NaN
1,270036,"December 27, 2014",California,Sacramento,4000 block of May Street,0,4,0,0,0,NaN
2,269679,"December 27, 2014",California,Los Angeles,8800 block of South Figueroa Street,1,3,0,0,0,NaN
3,269167,"December 26, 2014",Illinois,East St. Louis,2500 block of Summit Avenue,1,3,0,0,0,NaN
4,268598,"December 24, 2014",Missouri,Saint Louis,18th and Pine,1,3,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4688,2104725,"August 31, 2021",North Carolina,Elm City,3500 block of London Church Rd,2,2,0,0,1,NaN
4689,2104181,"August 30, 2021",Illinois,Normal,2000 block of Lambert Dr,2,3,1,0,0,NaN
4690,2103256,"August 29, 2021",Tennessee,Nashville,2621 Jefferson St,0,5,0,0,1,NaN
4691,2102991,"August 29, 2021",Nevada,Las Vegas,1750 S Rainbow Blvd,1,3,0,0,3,NaN
4692,2103311,"August 29, 2021",Wisconsin,Milwaukee,N 41st St and W Lloyd St,0,4,0,0,0,NaN